### ISSUE TITLE
Add aspnet example

### ISSUE THREAD

**Issue by dzmitry-lahoda** [YairHalberstadt/stronginject#33]

**Comment by dzmitry-lahoda** [comment]
i think i can try to do that within couple of months

**Comment by YairHalberstadt** [comment]
Thanks, that's great. I might get round to it sooner if I have time.
I've now implemented https://github.com/YairHalberstadt/stronginject/issues/38 which should make this easier.

**Comment by YairHalberstadt** [comment]
I've added an experimental package to help you integrate with IServiceCollection. More details [here](https://github.com/YairHalberstadt/stronginject/blob/master/README.md#integrate-with-aspnetcoremicrosoftextensionsdependencyinjection).

Please try it out and let me know what you think!

**Comment by arphox** [comment]
After reading some about the new source generators, I gave this repo's README a quick look but I just can't understand how could I use this. Maybe the documentation should be updated in a beginner-friendly manner, or it's just me, I don't know (otherwise I know multiple DI/IoC containers, I know how to use them, so I didn't mean I am new at IoC containers).

I think a demo ASP.NET Core 5.0 application that uses StrongInject and have some common scenarios would be a great boost for everyone to understand it. I may not be the only one who does not understand the whole concept.

If there are no other projects based on the same idea (writing an IoC container using source generators), I think this project can become popular later on, if it recieves enough dedication and attention.

**Comment by YairHalberstadt** [comment]
Hi @arphox 

Thanks for your feedback. I've now added a [sample project](https://github.com/YairHalberstadt/stronginject/tree/master/Samples/AspNetCore) showing usage of StrongInject with Asp.NetCore to this repo. Please let me know if there's any more scenarios you would like to see added to that project.

> Maybe the documentation should be updated in a beginner-friendly manner, or it's just me, I don't know (otherwise I know multiple DI/IoC containers, I know how to use them, so I didn't mean I am new at IoC containers).

It's a really difficult balance to strike between getting all the information necessary in the documentation, and making it easily accessible for beginners. I guess I've gone to far one way and it's useful to hear that's a problem.

I'm not brilliant at writing documentation, so any help on that part would be greatly appreciated.

If you do have any trouble using StrongInject you can always chat to me on [gitter](https://gitter.im/stronginject/community).

**Comment by arphox** [comment]
Thank you for the example!

I checked the sample project, and I thought I will create another controller.
So I created `AnotherController` which is an exact copy of the original `WeatherForecastController` (except that it is renamed).
This is all I did, I did not create any reference to the new controller class.

I built and started the application, but after a second it threw an exception:
```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: StrongInject.Samples.AspNetCore.Controllers.AnotherController Lifetime: Transient ImplementationType: StrongInject.Samples.AspNetCore.Controllers.AnotherController': Unable to resolve service for type 'System.Func`2[System.String,StrongInject.Samples.AspNetCore.Services.IWeatherForecastProvider]' while attempting to activate 'StrongInject.Samples.AspNetCore.Controllers.AnotherController'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at StrongInject.Samples.AspNetCore.Program.Main(String[] args) in d:\repos\stronginject\Samples\AspNetCore\Program.cs:line 16

  This exception was originally thrown at this call stack:
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(Microsoft.Extensions.DependencyInjection.ServiceDescriptor)

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: StrongInject.Samples.AspNetCore.Controllers.AnotherController Lifetime: Transient ImplementationType: StrongInject.Samples.AspNetCore.Controllers.AnotherController': Unable to resolve service for type 'System.Func`2[System.String,StrongInject.Samples.AspNetCore.Services.IWeatherForecastProvider]' while attempting to activate 'StrongInject.Samples.AspNetCore.Controllers.AnotherController'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'System.Func`2[System.String,StrongInject.Samples.AspNetCore.Services.IWeatherForecastProvider]' while attempting to activate 'StrongInject.Samples.AspNetCore.Controllers.AnotherController'.
```

Now I have two questions:
1. The url it was trying to reach is `https://localhost:44383/weatherforecast?location=London`. If I didn't refer to my other controller, why did it try to construct it? I didn't need that.
2. Where is the promised compile-time safety of the IoC container?

**Comment by YairHalberstadt** [comment]
> The url it was trying to reach is https://localhost:44383/weatherforecast?location=London. If I didn't refer to my other controller, why did it try to construct it? I didn't need that.

This is an Asp.Net issue - Asp.Net automatically tries to check all instances of a controller can be resolved. Since you haven't registered `AnotherController` it throws an error.

> Where is the promised compile-time safety of the IoC container?

Again this is an Asp.Net issue. Whilst StrongInject guarantees compile time safety for things it resolves, in this case Asp.Net is trying to resolve `AnotherController` without going through StrongInject.

To resolve this issue you might want to look into stopping Asp.Net from auto registering controllers. Take a look at https://stackoverflow.com/questions/56714360/automatic-controller-detection-in-asp-net-core for some hints as to how to do that.

**Comment by YairHalberstadt** [comment]
@arphox 

Can you try doing the following.

1. Add the following class to your application:

```csharp
public static class MvcBuilderExtensions
{
    /// <summary>
    /// Use the ServiceProvider to resolve controllers. Will error if the controller isn't explicitly registered
    /// </summary>
    /// <param name="builder">The <see cref="IMvcBuilder"/>.</param>
    /// <returns>The <see cref="IMvcBuilder"/>.</returns>
    public static IMvcBuilder ResolveControllersThroughServiceProvider(IMvcBuilder builder)
    {
        var feature = new ControllerFeature();
        builder.PartManager.PopulateFeature(feature);

        builder.Services.Replace(ServiceDescriptor.Transient<IControllerActivator, ServiceBasedControllerActivator>());

        return builder;
    }
}
```

Replace ConfigureServices with:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddContainerForTransientService<Container, WeatherForecastController>();
    services.AddControllers().ResolveControllersThroughServiceProvider();
}
```

This should stop Asp.Net from trying to construct `AnotherController` automatically.

**Comment by arphox** [comment]
Thank you for the code snippets, this resolves the "number one" problem which was: _"The url it was trying to reach is https://localhost:44383/weatherforecast?location=London. If I didn't refer to my other controller, why did it try to construct it? I didn't need that._"

> Again this is an Asp.Net issue. Whilst StrongInject guarantees compile time safety for things it resolves, in this case Asp.Net is trying to resolve AnotherController without going through StrongInject.

Is the compile time safety impossible for ASP.NET Core applications, then?

**Comment by YairHalberstadt** [comment]
> Is the compile time safety impossible for ASP.NET Core applications, then?

Since Asp.Net uses it's own DI framework, and it's impossible to replace it completely with StrongInject, complete compile time safety is impossible with Asp.Net.

However StrongInject allows you to get compile time safety within a scope.

For example, in the sample project you wont get any errors or warning if another controller can't be created. However you will get errors if StrongInject cant resolve the `WeatherForecastController`, since you resolve that using StrongInject.

My advice is to try to move as much as possible inside the StrongInject container. that way the potential for runtime errors is reduced.

What that means is you use StrongInject containers to resolve all your controllers, and then register the containers with Asp.Net. You don't need to register any services used by these containers with Asp.Net since StrongInject takes care of that for you.

**Comment by arphox** [comment]
Thank you.

> complete compile time safety is impossible with Asp.Net.
This should be heavily emphasized on the main page of the documentation, I think this is really important. I believe C# is probably most used for web apps with ASP.NET Core.

> However you will get errors if StrongInject cant resolve the WeatherForecastController, since you resolve that using StrongInject.
If I remove the line `services.AddContainerForTransientService<Container, WeatherForecastController>();` from `Startup.cs`'s `ConfigureServices` method, the application builds and fails at runtime. This is equivalent as forgetting to register a type, which it seems the users are not defended against in ASP.NET Core. I know this is because of asp, but still, it is present.

I think the whole problem with the loss of compile time safety begins with losing the control of resolving. I understand that in a console application (where you have full control on the control flow) compile-time safety is possible, but then it seems like in all other cases (which means the vast majority of C# applications, like ASP.NET Core, WPF, etc) it is probably not.

Since this IoC container is so unique and works differently, I believe people need extensive guidance on how to integrate this container into their applications, regardless of their framework type. Until that, I don't think people will start using it. I believe they won't understand what this is all about.

We need to find the best possible practice for the most popular frameworks (ASP.NET Core, WPF, Unity, Xamarin, etc), document and present it.

Speaking of the current AspNetCore, I recommend extending it further (contain at least 3 controllers, etc), because based on the current state I think the usage (adding additional controllers) is not straightforward.

**Comment by YairHalberstadt** [comment]
> Speaking of the current AspNetCore, I recommend extending it further (contain at least 3 controllers, etc), because based on the current state I think the usage (adding additional controllers) is not straightforward.

I've added another example controller to the sample project. I don't believe adding more would be beneficial, as the process is exactly the same for each controller.

> We need to find the best possible practice for the most popular frameworks (ASP.NET Core, WPF, Unity, Xamarin, etc), document and present it.

I would definitely like to write more sample projects. Obviously I'm limited in the amount of time I have available - I work full time, and this can only be a side project. However I do put a lot of time into this project, and the quality of the documentation is slowly improving.

> I think the whole problem with the loss of compile time safety begins with losing the control of resolving. I understand that in a console application (where you have full control on the control flow) compile-time safety is possible, but then it seems like in all other cases (which means the vast majority of C# applications, like ASP.NET Core, WPF, etc) it is probably not.

I think this is actually pretty specific to Asp.Net. Full compile time safety should be possible with WPF for example. Either way, I think the important thing is that people are clear as to what StrongInject guarantees and what it doesn't, and thereby understand the benefits StrongInject provides and how to make the most of them. I hope to add a section on this to the readme soon.

**Comment by kolpav** [comment]
@YairHalberstadt Hi, I wanted to give to try strong inject so I opened the asp.net sample but it makes assumption you are using controllers. Is there such a thing as drop in replacement for MS DI asp.net projects or do you need to choose different approaches depending on how your project?
Could packages which works without configuration with asp.net default require some additional tinkering if you use strong inject? Why I am asking is that I would like to avoid scenario where I add some package in the future and need to spend hours figuring out how to make it work with strong inject or even not be able to figure it out at all and only solution being to remove strong inject.

To give you better idea about my project it is trying to use the MS recommended approaches whenever possible without doing anything fancy what makes it unique is not using REST but [GraphQL](https://github.com/ChilliCream/hotchocolate) which doesn't have concept of resource endpoints there is just one accepting graphql requests.
I would like to replace my mapping and DI with build time ones while at the same time having deadline to make so I don't have that much time to experiment as I would like to unfortunately.
Awesome project btw 🙏  generating code at build time is feature I am most excited about the possibilities are endless.
