### ISSUE TITLE
Strong Inject Logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [YairHalberstadt/stronginject#89]
So [@ACPWintiate](https://twitter.com/acpwintiate) and I are experimenting with a few ideas. Here is an initial idea, but please feel free to give feedback.

![image](https://user-images.githubusercontent.com/228256/100919223-81651400-34a7-11eb-8a5f-27a44d8eb2a9.png)

**Comment by khalidabuhakmeh** [comment]
cc @onelioubov @jnm2

**Comment by YairHalberstadt** [comment]
Hi @khalidabuhakmeh 

Thanks so much for your ideas and time - really appreciated!

Could you explain what the box is meant to represent since I didn't fully understand?

@onelioubov also sent some ideas:

![image](https://user-images.githubusercontent.com/29174528/100919868-0e798e80-34e3-11eb-9df3-63225ad7595b.png)
![image](https://user-images.githubusercontent.com/29174528/100919853-09b4da80-34e3-11eb-845e-f893f357747d.png)
![image](https://user-images.githubusercontent.com/29174528/100919896-146f6f80-34e3-11eb-96b0-73c13df6b56b.png)

![image](https://user-images.githubusercontent.com/29174528/100919917-1c2f1400-34e3-11eb-81b3-5b2a9794d394.png)
![image](https://user-images.githubusercontent.com/29174528/100919929-2224f500-34e3-11eb-9f90-75216f893991.png)
![image](https://user-images.githubusercontent.com/29174528/100919938-281ad600-34e3-11eb-856d-10c5680f56b9.png)

There's bits I really like from all of them - for example I really like the font and layout of your text, I like the way the syringe becomes the T in @onelioubov first set of ideas, and I really like the simplicity of the icon in @onelioubov seconds set of ideas!

If there was some way of combining some of those elements that would be awesome :-)

I'm not particularly artistic, so I'm not going to be hugely useful beyond that. I guess the best I can do is put it to the people to get some feedback.

Once again the effort you've put into this is hugely appreciated!

**Comment by YairHalberstadt** [comment]
Here's a concept I hacked together on paint combining your ideas. Not sure if it has much merit :-)

![image](https://user-images.githubusercontent.com/29174528/100921139-cf4c3d00-34e4-11eb-8882-ee3e0edd0c0f.png)

**Comment by khalidabuhakmeh** [comment]
Here's another one. I'm just playing around. 

![image](https://user-images.githubusercontent.com/228256/100928106-cf801480-34b3-11eb-99dd-3f5da43b1a08.png)

**Comment by khalidabuhakmeh** [comment]
@YairHalberstadt it's a safe, so it locks stuff inside. :)

**Comment by khalidabuhakmeh** [comment]
![image](https://user-images.githubusercontent.com/228256/100930994-e1fc4d00-34b7-11eb-9829-69185d45b2cd.png)

**Comment by YairHalberstadt** [comment]
> @YairHalberstadt it's a safe, so it locks stuff inside. :)

So you're referencing the Strong! I was trying to work out what it had to do with inject!

Thanks for the new logos!

I think this looks really good: 
![image](https://user-images.githubusercontent.com/29174528/100967693-82925180-3538-11eb-8e98-9ea361a24d2b.png)

I think this would look a little better without the circle. Since it's not symmetrical, it looks a little off center:

![image](https://user-images.githubusercontent.com/29174528/100968199-8f637500-3539-11eb-8d97-774a847a238f.png)


![image](https://user-images.githubusercontent.com/29174528/100968458-0ef14400-353a-11eb-9149-1b7fbbb77631.png)

All really cool stuff, greatly appreciated!

**Comment by khalidabuhakmeh** [comment]
![horizontal@2x](https://user-images.githubusercontent.com/228256/101084464-fbff6380-357b-11eb-967c-ce69b32f1fc4.png)

![stand-alone@2x](https://user-images.githubusercontent.com/228256/101084473-fefa5400-357b-11eb-9d30-2bcc0aa6d7a4.png)

I've included PNGs and SVGs of the logo. 👍 

[logo.zip](https://github.com/YairHalberstadt/stronginject/files/5638763/logo.zip)

**Comment by YairHalberstadt** [comment]
Thank you so much! Is there any particular way you want me to credit you for the logo? Anything you'd like to use this as an opportunity to advertise? Would you like to create a PR so that you appear in git history as having added the logo, and are added to the contributors list?

Else I'll add the logos myself, and under the logo in the README.md write:

> Logo kindly contributed by @khalidabuhakmeh and @onelioubov

**Comment by khalidabuhakmeh** [comment]
You should put @onelioubov first, but that's fine. She did most of the work :)

**Comment by onelioubov** [comment]
Sorry for the late response. I made a small tweak to the logo @khalidabuhakmeh kindly put together (and I think we both did about the same amount of work :) ). If you're already using the other one though, that's totally fine!

![logo-10](https://user-images.githubusercontent.com/7337388/101173999-4979e000-3611-11eb-917a-7e55cf4369d7.png)

**Comment by onelioubov** [comment]
And in case you need the colors for branding reasons, here they are:

#1D3557
#FFD7A6
#457B9D

**Comment by YairHalberstadt** [comment]
Thanks @onelioubov - I think I prefer that! Can you send me the small icon for that, and the SVG please too? Thanks

**Comment by onelioubov** [comment]
Sure! Here you go.

[strong-inject.zip](https://github.com/YairHalberstadt/stronginject/files/5645933/strong-inject.zip)

**Comment by onelioubov** [comment]
Yes, here you go! 😄 
[stronginject.zip](https://github.com/YairHalberstadt/stronginject/files/5646067/stronginject.zip)
